name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - build.yaml
      - CMakeLists.txt
      - Kconfig
      - zephyr/**
      - src/**

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
